{
    "name": "MirrorNc",
    "author": "hachkingtohach1",
    "api": [
        "3.0.0", "3.14.0", "3.14.1", "3.14.2", "3.14.3", 
    ],
    "mcpe-protocol": [
        "361", "388", "389", "390", "407", "408"
    ],
    "version": "1.0.0",
    "main": "hachkingtohach1\\MirrorNc\\MirrorNc",
    "website": "https://watchshit.weebly.com/",
    "description": "Plugin MirrorNc, one system atnilagg and optimization pro for pocketmine_pmmp",
    "permissions": {}
}